substitutions:
  clk_pin: GPIO5
  mosi_pin: GPIO23
  cs_pin: GPIO21
  num_chips: "4"


# Use ESP IDF framework
esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

ota:
  platform: esphome
  password: ${ota_pw}

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  on_connect:
    then:
      - lambda: |-
          ESP_LOGI("$TAG", "WiFi Connect");
          id(trigger_rendering).execute();
          
  on_disconnect:
    then:
      - lambda: |-
          ESP_LOGI("$TAG", "WiFi Disconnect");
          id(trigger_rendering).execute();

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${fallback_hotspot_ssid} 
    password: ${fallback_hotspot_pw} 
    

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Displays a notification in case the device need to be updated
dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true


# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# To have a "next url" for improv serial
#web_server:
#  port: 80
#  version: 3



# Configure LED Matrix Pinout
spi:
  clk_pin:     
    number: $clk_pin
    ignore_strapping_warning: true
  mosi_pin: $mosi_pin

# time:
#  - platform: homeassistant
#    id: hass_time

#image:
#  - file: "smile.png"
#    id: my_image






